"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
APP_NAME = 'BPK'
APP = ['main.py']
DATA_FILES = [
        ('db',['db/bpk.db']),
        ('db',['db/шаблон.docx']),
                ]
OPTIONS = { 'packages': ['altgraph' ,'babel','DateTime','docopt','docxcompose', 'pyside6',
                         'docxtpl','jinja2','lxml','markupsafe','modulegraph','pymorphy2',
                         'pytz','setuptools','shiboken6','sqlalchemy','wheel'],
            'iconfile':'icon.icns',
           'argv_emulation':True,
           }

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
